import './energySubstation.css';
import {loadSubstation,buySubstation,addSubstationBudget,withdrawSubstationMoney,loadTransformer,buyTransformer,acceptSupply,toggleSupply,offerHousePower,loadPowerInbox,answerPowerOffer,getSubstationError} from './energySubstationApi.js';

const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money=v=>`${Math.max(0,Math.round(Number(v)||0)).toLocaleString('ru-RU')} ₴`;
const qty=v=>Math.max(0,Number(v)||0).toLocaleString('ru-RU',{maximumFractionDigits:2});
const toast=(message,type='info')=>window.dispatchEvent(new CustomEvent('mn:toast',{detail:{message,type}}));
const typeOf=o=>{const raw=String(o?.type||'');return raw==='marker'?String(o?.payload?.jobType||o?.payload?.type||raw):String(raw||o?.payload?.jobType||o?.payload?.type||'');};
const idOf=o=>String(o?.payload?.substationId||o?.payload?.substation_id||o?.payload?.transformerId||o?.payload?.transformer_id||o?.id||'').trim();

function shell(){return `<div class="mn-substation-backdrop" data-substation-modal hidden><section class="mn-substation-panel"><header><div><small data-substation-eyebrow>ЭНЕРГЕТИЧЕСКОЕ ПРЕДПРИЯТИЕ</small><h2 data-substation-title>Подстанция</h2><p data-substation-subtitle>Электростанция → подстанция → трансформаторы → потребители</p></div><button data-substation-close>×</button></header><nav class="mn-substation-tabs" data-substation-tabs><button class="is-active" data-substation-tab="overview">Обзор</button><button data-substation-tab="supply">Поставщики</button><button data-substation-tab="transformers">Трансформаторы</button><button data-substation-tab="consumers">Потребители</button></nav><main data-substation-content></main></section></div><button class="mn-substation-inbox" data-power-inbox hidden>⚡ Договор электроснабжения</button>`;}

export function enableEnergySubstationFeature({root,cityId}={}){
  if(!root)return()=>{};root.insertAdjacentHTML('beforeend',shell());
  const modal=root.querySelector('[data-substation-modal]'),content=modal.querySelector('[data-substation-content]'),tabs=modal.querySelector('[data-substation-tabs]'),inboxButton=root.querySelector('[data-power-inbox]');
  let currentId='',mode='substation',snapshot=null,activeTab='overview',busy=false,inbox={offers:[]},timer=0,liveTimer=0;
  const close=()=>{modal.hidden=true;window.clearInterval(liveTimer);liveTimer=0;};
  const syncBalance=result=>{const balance=Number(result?.playerBalance);if(Number.isFinite(balance))window.dispatchEvent(new CustomEvent('mn:player-balance-changed',{detail:{balance,source:'energy_substation'}}));};
  const run=async(task,message)=>{if(busy)return;busy=true;modal.querySelector('.mn-substation-panel').classList.add('is-busy');try{const result=await task();syncBalance(result);if(mode==='substation')snapshot=await loadSubstation(currentId,cityId);else if(mode==='transformer')snapshot=await loadTransformer(currentId,cityId);else inbox=await loadPowerInbox();syncBalance(mode==='inbox'?inbox:snapshot);render();await refreshInbox();if(message)toast(message,'success');}catch(e){toast(getSubstationError(e),'error');}finally{busy=false;modal.querySelector('.mn-substation-panel').classList.remove('is-busy');}};
  const setTab=name=>{activeTab=name;modal.querySelectorAll('[data-substation-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.substationTab===name));render();};

  function overview(){const s=snapshot||{},plant=s.plant||{};if(!plant.ownerId)return `<section class="mn-substation-page"><div class="mn-substation-buy"><span><small>ГОСУДАРСТВЕННАЯ ПОДСТАНЦИЯ</small><strong>1 000 000 ₴</strong><p>Налоговая форма задаётся администрацией при размещении объекта.</p></span><button class="is-primary" data-substation-buy>Купить предприятие</button></div></section>`;return `<section class="mn-substation-page"><div class="mn-substation-stats"><article><small>Владелец</small><strong>${esc(plant.ownerName||'—')}</strong></article><article><small>Счёт предприятия</small><strong>${money(s.cashBalance)}</strong></article><article><small>Получено энергии</small><strong>${qty(s.energyReceivedKwh)} кВт·ч</strong></article><article><small>Продано энергии</small><strong>${qty(s.energySoldKwh)} кВт·ч</strong></article></div><div class="mn-substation-flow">ГЭС / АЭС / УЭС → закупка по контракту → трансформаторы → дома</div>${s.isOwner?`<div class="mn-substation-form"><input data-substation-budget type="number" min="1" value="100000" placeholder="Сумма"><button data-substation-add-budget>Пополнить счёт</button><input data-substation-withdraw type="number" min="1" value="1000" placeholder="Сумма"><button data-substation-withdraw-btn>Снять прибыль</button></div>`:''}<div class="mn-substation-list"><article class="mn-substation-card"><span><small>Расходы на поставки</small><b>${money(s.sourceCosts)}</b></span><span><small>Амортизация трансформаторов</small><b>${money(s.maintenanceCosts)}</b></span><span><small>Выручка</small><b>${money(s.revenue)}</b></span></article></div></section>`;}
  function supply(){const offers=snapshot?.supplyOffers||[],links=snapshot?.supplyLinks||[];return `<section class="mn-substation-page"><h3>Контракты с электростанциями</h3><p>Энергия оплачивается по каждому фактически переданному кВт·ч. Сумма договора ограничивает общий объём закупки.</p><div class="mn-substation-list">${offers.length?offers.map(o=>`<article class="mn-substation-card"><span><small>${esc(o.sourceLabel)} · предложение</small><b>${money(o.unitPrice)} / кВт·ч</b><em>Лимит договора: ${money(o.contractAmount)}</em></span>${snapshot?.isOwner?`<button data-supply-accept="${esc(o.id)}" data-source="${esc(o.sourceType)}">Принять</button>`:''}</article>`).join(''):'<div class="mn-substation-empty">Новых предложений от электростанций нет.</div>'}</div><h3 style="margin-top:22px">Активные поставщики</h3><div class="mn-substation-list">${links.length?links.map(l=>`<article class="mn-substation-card"><span><small>${esc(l.sourceLabel)}</small><b>${money(l.unitPrice)} / кВт·ч</b><em>Использовано ${money(l.spent)} из ${money(l.contractLimit)}</em></span>${snapshot?.isOwner?`<button data-supply-toggle="${esc(l.id)}" data-enabled="${l.active?'0':'1'}">${l.active?'Остановить':'Возобновить'}</button>`:''}</article>`).join(''):'<div class="mn-substation-empty">Нет принятых контрактов.</div>'}</div></section>`;}
  function transformers(){const rows=snapshot?.transformers||[];return `<section class="mn-substation-page"><h3>Трансформаторы</h3><p>Покупаются отдельно возле трансформаторных пикапов. Лимит — 5 на одну подстанцию, 6 потребителей на каждый.</p><div class="mn-substation-list">${rows.length?rows.map(t=>`<article class="mn-substation-card"><span><small>ID ${esc(t.id)}</small><b>${t.active?'⚡ Работает':'⛔ Остановлен'}</b><em>${t.consumerCount}/6 потребителей · 300 кВт · амортизация 400 ₴/сутки</em></span></article>`).join(''):'<div class="mn-substation-empty">Трансформаторов пока нет.</div>'}</div></section>`;}
  function consumers(){const houses=snapshot?.availableHouses||[],contracts=snapshot?.consumers||[];return `<section class="mn-substation-page"><h3>Подключение потребителей</h3><p>Дом расходует 5 кВт·ч в час. Владелец дома сам принимает или отклоняет предложение.</p>${snapshot?.isOwner?`<div class="mn-substation-form"><select data-power-house>${houses.map(h=>`<option value="${esc(h.houseId)}" data-transformer="${esc(h.transformerId)}">${esc(h.ownerName)} · ${esc(h.houseName||h.houseId)} · трансформатор ${esc(h.transformerId)}</option>`).join('')}</select><input data-power-tariff type="number" min="0.01" step="0.01" value="4" placeholder="₴ за кВт·ч"><input data-power-connection type="number" min="500" value="2000" placeholder="Подключение"><button data-power-offer ${houses.length?'':'disabled'}>Предложить договор</button></div>`:''}<div class="mn-substation-list">${contracts.length?contracts.map(c=>`<article class="mn-substation-card"><span><small>${esc(c.houseName||c.houseId)} · ${esc(c.consumerName||'владелец')}</small><b>${c.status==='active'?(c.powerActive?'⚡ Свет подключён':'⚠️ Подача приостановлена'):c.status==='offered'?'Ожидает решения':'Отклонён'}</b><em>${money(c.retailPrice)} / кВт·ч · подключение ${money(c.connectionFee)} · использовано ${qty(c.totalKwh)} кВт·ч</em></span></article>`).join(''):'<div class="mn-substation-empty">Потребителей пока нет.</div>'}</div></section>`;}
  function transformerView(){const t=snapshot?.transformer||{},subs=snapshot?.mySubstations||[];if(t.substationId)return `<section class="mn-substation-page"><div class="mn-substation-buy"><span><small>ТРАНСФОРМАТОР ЗАКРЕПЛЁН</small><strong>${esc(t.substationName||t.substationId)}</strong><p>300 кВт · до 6 конечных потребителей.</p></span></div></section>`;return `<section class="mn-substation-page"><div class="mn-substation-buy"><span><small>ИНЖЕНЕРНЫЙ УЗЕЛ</small><strong>3 000 000 ₴</strong><p>Выберите принадлежащую вам подстанцию. После покупки перенести трансформатор нельзя.</p></span></div><div class="mn-substation-form"><select data-transformer-substation>${subs.map(s=>`<option value="${esc(s.id)}">${esc(s.name||s.id)} · ${s.transformerCount}/5</option>`).join('')}</select><button class="is-primary" data-transformer-buy ${subs.length?'':'disabled'}>Купить трансформатор</button></div></section>`;}
  function inboxView(){const offers=inbox.offers||[];return `<section class="mn-substation-page"><h3>Предложения электроснабжения</h3><div class="mn-substation-list">${offers.length?offers.map(o=>`<article class="mn-substation-card"><span><small>${esc(o.substationName)} · дом ${esc(o.houseName||o.houseId)}</small><b>${money(o.retailPrice)} / кВт·ч</b><em>Подключение и работа бригады: ${money(o.connectionFee)} · потребление 5 кВт·ч/час</em></span><div><button class="is-primary" data-power-answer="${esc(o.id)}" data-accept="1">Принять</button> <button data-power-answer="${esc(o.id)}" data-accept="0">Отказаться</button></div></article>`).join(''):'<div class="mn-substation-empty">Новых предложений нет.</div>'}</div></section>`;}
  function render(){tabs.hidden=mode!=='substation';content.innerHTML=mode==='transformer'?transformerView():mode==='inbox'?inboxView():activeTab==='overview'?overview():activeTab==='supply'?supply():activeTab==='transformers'?transformers():consumers();bind();}
  function bind(){content.querySelector('[data-substation-buy]')?.addEventListener('click',()=>run(()=>buySubstation(currentId,cityId),'Подстанция приобретена.'));content.querySelector('[data-substation-add-budget]')?.addEventListener('click',()=>run(()=>addSubstationBudget(currentId,cityId,Number(content.querySelector('[data-substation-budget]').value)),'Счёт пополнен.'));content.querySelector('[data-substation-withdraw-btn]')?.addEventListener('click',()=>run(()=>withdrawSubstationMoney(currentId,cityId,Number(content.querySelector('[data-substation-withdraw]').value)),'Деньги выведены.'));content.querySelector('[data-transformer-buy]')?.addEventListener('click',()=>run(()=>buyTransformer(currentId,cityId,content.querySelector('[data-transformer-substation]').value),'Трансформатор закреплён за подстанцией.'));content.querySelectorAll('[data-supply-accept]').forEach(b=>b.onclick=()=>run(()=>acceptSupply(currentId,cityId,b.dataset.source,b.dataset.supplyAccept),'Контракт поставки принят.'));content.querySelectorAll('[data-supply-toggle]').forEach(b=>b.onclick=()=>run(()=>toggleSupply(currentId,cityId,b.dataset.supplyToggle,b.dataset.enabled==='1'),'Статус поставщика изменён.'));content.querySelector('[data-power-offer]')?.addEventListener('click',()=>{const select=content.querySelector('[data-power-house]'),option=select?.selectedOptions?.[0];if(!option)return;run(()=>offerHousePower(currentId,cityId,{houseId:select.value,transformerId:option.dataset.transformer,retailPrice:Number(content.querySelector('[data-power-tariff]').value),connectionFee:Number(content.querySelector('[data-power-connection]').value)}),'Предложение отправлено владельцу дома.');});content.querySelectorAll('[data-power-answer]').forEach(b=>b.onclick=()=>run(()=>answerPowerOffer(b.dataset.powerAnswer,b.dataset.accept==='1'),b.dataset.accept==='1'?'Электричество подключено.':'Предложение отклонено.'));}
  async function openObject(object){currentId=idOf(object);if(!currentId)return;mode=typeOf(object)==='power_transformer'?'transformer':'substation';activeTab='overview';modal.hidden=false;modal.querySelector('[data-substation-title]').textContent=mode==='transformer'?'Силовой трансформатор':'Электрическая подстанция';modal.querySelector('[data-substation-subtitle]').textContent=mode==='transformer'?'300 кВт · максимум 6 потребителей':'Электростанции → подстанция → трансформаторы → дома';window.clearInterval(liveTimer);try{snapshot=mode==='transformer'?await loadTransformer(currentId,cityId):await loadSubstation(currentId,cityId);syncBalance(snapshot);render();if(mode==='substation')liveTimer=window.setInterval(async()=>{if(modal.hidden||busy||mode!=='substation'||activeTab!=='overview')return;try{snapshot=await loadSubstation(currentId,cityId);syncBalance(snapshot);render();}catch{}},15000);}catch(e){toast(getSubstationError(e),'error');}}
  async function refreshInbox(){try{inbox=await loadPowerInbox();inboxButton.hidden=!(inbox?.offers?.length);}catch{inboxButton.hidden=true;}}
  const onAction=e=>{const object=e.detail?.object;if(['energy_substation','power_transformer'].includes(typeOf(object)))void openObject(object);};window.addEventListener('mn:energy-substation-object-action',onAction);
  modal.querySelector('[data-substation-close]').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close();});tabs.addEventListener('click',e=>{const b=e.target.closest('[data-substation-tab]');if(b)setTab(b.dataset.substationTab);});inboxButton.onclick=async()=>{mode='inbox';currentId='';tabs.hidden=true;modal.querySelector('[data-substation-title]').textContent='Договор электроснабжения';modal.hidden=false;await refreshInbox();render();};
  const key=e=>{if(e.key==='Escape'&&!modal.hidden)close();};window.addEventListener('keydown',key);void refreshInbox();timer=window.setInterval(refreshInbox,30000);
  return()=>{window.clearInterval(timer);window.clearInterval(liveTimer);window.removeEventListener('keydown',key);window.removeEventListener('mn:energy-substation-object-action',onAction);modal.remove();inboxButton.remove();};
}
