import { supabase } from '../supabaseClient.js';
export async function vehicleRequest(cityId,id='',action='snapshot',data={},requestId=crypto.randomUUID()) {
 const initData=window.Telegram?.WebApp?.initData;if(!initData)throw Error('Откройте игру через Telegram.');
 const {data:r,error}=await supabase.functions.invoke('vehicle-industry',{body:{initData,cityId,id,action,data,requestId}});
 if(error){let msg=error.message;try{msg=(await error.context.clone().json()).error||msg;}catch{}throw Error(msg);}
 if(!r?.ok)throw Error(r?.error||'Не удалось выполнить действие.');return r.result;
}
const messages={AUTO_RESERVE_EMPTY:'В личном запасе не хватает подходящего топлива. Купите его на АЗС.',AUTO_TRANSIT:'Машина ещё в пути. Дождитесь времени прибытия.',AUTO_BORDER:'Для выезда подъедьте к краю карты на исправной машине.',AUTO_PRICE_CHANGED:'Тариф изменился. Обновите окно и подтвердите новую цену.',AUTO_FUNDS:'Недостаточно денег на оплачивающем счёте.',AUTO_OWNER:'Нужны права владельца.',AUTO_BATCH:'Текущая сборка ещё не завершена. Откройте предприятие после окончания таймера.',AUTO_STOCK:'На складе не хватает материалов или топлива.',AUTO_NEAR:'Вы слишком далеко: для посадки подойдите к машине, для обслуживания подъедьте к предприятию.',AUTO_EQUIPMENT:'Сначала установите сборочную линию.',AUTO_KITS:'Нет подходящего ремкомплекта.',AUTO_NEED_SERVICE:'Достигнут предел аварийного ремонта. Нужен ремонт на СТО.',AUTO_STOPPED:'Двигатель заглох: проверьте топливо и состояние.',AUTO_DRIVER:'Устройтесь водителем в выбранный логистический центр.',AUTO_HUB:'Выберите купленный логистический центр.',AUTO_TANK:'Укажите объём от 1 л, не превышающий свободное место в баке.',AUTO_ROUTE_ACTIVE:'Сначала завершите текущий рейс.',AUTO_OFFER:'Предложение уже недоступно.',AUTO_STATION:'АЗС закрыта, требует обслуживания или находится слишком далеко.',AUTO_DRIVING:'Сначала сядьте в автомобиль.',AUTO_CITY:'Автомобиль находится в другом городе.',AUTO_SPEED:'Позиция машины не прошла проверку. Повторите движение.',AUTO_PRICE:'Цена ниже минимальной.',AUTO_FULL:'Автомобиль уже полностью исправен.',AUTO_INVALID:'Проверьте введённые значения.',AUTO_DRIVER_DELIVERY_REQUIRED:'Эта партия передана выбранной транспортной компании.'};
export const vehicleError=e=>Object.entries(messages).find(([k])=>String(e?.message).includes(k))?.[1]||String(e?.message||e);

