import './vehicleIndustry.css';
import {state,save} from '../state.js';
import {vehicleRequest,vehicleError} from './vehicleIndustryApi.js';
import {playCargoTransferMiniGame} from '../logistics/cargoTransferMiniGame.js';
import {getMapObjects} from '../mapObjects/mapObjectsRepository.js';
export const AUTO_TYPES=['car_factory','car_dealer','auto_service'];
const labels={car_factory:'Автомобильный завод',car_dealer:'Автосалон',auto_service:'СТО',light:'Легковые',medium:'Средние',heavy:'Тягачи',petrol:'А-95',petrol92:'А-92',diesel:'Дизель',car_frame:'Каркас автомобиля',car_engine:'Двигатель автомобиля',car_body:'Кузов автомобиля',support_beam:'Опорная балка',screws:'Шурупы',rivets:'Заклёпки'};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const carSvg=color=>`<svg viewBox="0 0 32 52" width="30" height="48"><rect x="2" y="9" width="28" height="9" rx="2" fill="#111"/><rect x="2" y="35" width="28" height="9" rx="2" fill="#111"/><rect x="5" y="2" width="22" height="48" rx="7" fill="${/^#[0-9a-f]{6}$/i.test(color)?color:'#ffffff'}" stroke="#182731"/><path d="M8 14h16v10H8zM8 35h16v8H8z" fill="#376278"/><path d="M8 6h5m6 0h5" stroke="#fff3a0" stroke-width="3"/></svg>`;
const money=v=>Number(v||0).toLocaleString('ru-RU',{maximumFractionDigits:2})+' ₴';
export function enableVehicleIndustry({root,cityId,playerPosition,playerMarker}) {
 const actor=String(window.Telegram?.WebApp?.initDataUnsafe?.user?.id||'');
 const dialog=document.createElement('dialog');dialog.className='mn-auto-dialog';root.append(dialog);
 const launch=document.createElement('button');launch.className='mn-auto-launch';launch.textContent='🚘 Авто / перевозки';root.append(launch);
 const hud=document.createElement('div');hud.className='mn-auto-status';root.append(hud);
 const layer=document.createElement('div');root.querySelector('.gta-map-entities')?.append(layer);
 let s=null,id='',type='',busy=false,destroyed=false,tab='garage',notice='',objects=[],moving=false,retry=null;
 const btn=(a,label,data='',disabled=false)=>`<button data-action="${a}" ${data} ${busy||disabled?'disabled':''}>${label}</button>`;
 const field=(name,val=1)=>`<input data-field="${name}" type="number" value="${val}" min="1">`;
 const val=k=>dialog.querySelector(`[data-field="${k}"]`)?.value;
 const current=()=>s?.vehicles?.find(v=>v.owner_id===actor&&v.driving);
 const model=v=>s.models.find(m=>m.id===v.model);
 const hubs=()=>`<label>Перевозчик <select data-field="hub"><option value="">Выберите компанию</option>${(s.hubs||[]).map(h=>`<option value="${esc(h.id)}">${esc(h.name||h.id)} · ${esc(h.city)}</option>`).join('')}</select></label><label>Оплата водителю ${field('reward',250)}</label>`;
 function render(){if(!s||destroyed)return;
 const focused=document.activeElement?.dataset?.field;
 const drafts=new Map([...dialog.querySelectorAll('[data-field]')].map(e=>[e.dataset.field,e.value]));
 const b=s.business,own=b?.owner_id===actor,car=current();let html='';
 if(tab==='garage')html=`<p>F — сесть рядом с машиной / выйти. WASD — движение. H рядом с АЗС — заправка в бак. Клавиши работают по физическому расположению.</p><p>Аварийных ремкомплектов: ${s.kits}. Каждый +50 состояния, максимум 70% полной прочности; дальше нужен ремонт на СТО.</p>`+s.vehicles.filter(v=>v.owner_id===actor).map(v=>{const m=model(v);return `<article><h3>${esc(m.label)} ${v.used?'· б/у':''} ${v.route_id?'· служебный':''}</h3><p>${esc(v.city_id)} · ${Number(v.condition).toFixed(1)} / ${m.max_condition} · глохнет при ≤ ${m.stop_condition}</p><p>${labels[m.fuel_type]} · ${Number(v.fuel).toFixed(2)} / ${m.tank} л · ${m.consumption} л/100 км</p>${btn(v.driving?'exit':'enter',v.driving?'Выйти':'Сесть',`data-vehicle="${v.id}"`)}${btn('repair_kit','Использовать аварийный комплект',`data-vehicle="${v.id}"`)}<p>При пустом баке можно купить подходящее топливо пешком на АЗС и перелить из личного запаса.</p>${field('reserve-'+v.id,5)}${btn('reserve_refuel','Залить из личного запаса',`data-vehicle="${v.id}"`)}<input data-field="color-${v.id}" type="color" value="${esc(v.color)}">${btn('paint','Покрасить',`data-vehicle="${v.id}"`)}${v.driving?`<p>Межгород: подъедьте к краю карты. Условный участок — 50 км / 60 сек.</p><select data-field="city">${s.cities.filter(c=>c!==cityId).map(c=>`<option>${esc(c)}</option>`).join('')}</select>${v.transit_ready?`<p>В пути до ${new Date(v.transit_ready).toLocaleTimeString()}</p>${btn('arrive','Прибыть',`data-vehicle="${v.id}"`,Date.parse(v.transit_ready)>Date.now())}`:btn('travel','Выехать из города',`data-vehicle="${v.id}"`)}`:''}</article>`;}).join('');
 if(tab==='business'){
 html=`<h3>${labels[type]||'Предприятие'}</h3><p>ID для коммунальных подключений: <code>${esc(id)}</code></p>`;
 if(!b?.owner_id)html+=`<p>Стоимость: ${money(type==='car_factory'?5000000:type==='car_dealer'?2000000:1000000)}</p>${btn('purchase','Купить предприятие')}`;
 if(own){html+=`<p>Счёт: ${money(b.cash)}</p>${field('amount',10000)}${btn('deposit','Пополнить')}${btn('withdraw','Снять')}<hr>`;
 if(type==='car_factory')html+=!b.equipment?`<p>Сборочная линия: 1 000 000 ₴</p>${btn('equipment','Установить линию','',Number(b.cash)<1000000)}`:`<p>Склад: ${s.stock.map(t=>`${labels[t.item]||esc(t.item)} × ${t.quantity}`).join(', ')||'пусто'}</p><p>${b.batch_ready?'Сборка до '+new Date(b.batch_ready).toLocaleTimeString():'Линия свободна'}</p>${s.models.map(m=>`<article><b>${esc(m.label)} · опт ${money(m.wholesale)}</b><p>${Object.entries(m.recipe).map(([k,q])=>`${labels[k]||esc(k)} × ${q}`).join(' + ')}</p>${btn('assemble','Собрать за 60 секунд',`data-model="${m.id}"`,!!b.batch_ready)}</article>`).join('')}<h3>Выбор поставщика компонентов</h3>${hubs()}${s.offers.map(o=>`<article>${esc(o.factory_id)} · ${esc(o.city_id)} · ${labels[o.product_type]||esc(o.product_type)} × ${o.quantity} · ${money(o.quantity*o.unit_price)}${btn('components_buy','Купить партию и заказать перевозку',`data-offer="${o.id}"`)}</article>`).join('')}`;
 if(type==='car_dealer')html+=`<h3>Заказ у выбранного завода</h3>${hubs()}${s.carsForSale.map(v=>`<article>${esc(model(v).label)} · ${esc(v.business_id)} · ${esc(v.city_id)} · ${money(model(v).wholesale)}${btn('car_order','Заказать перевозку',`data-vehicle="${v.id}"`)}</article>`).join('')}<h3>Подержанные автомобили</h3><p>Закупка у государственного поставщика: 15 000 ₴. Продажа новичкам: 20 000 ₴; состояние 200/500, в баке 5 л.</p>${['compact','sedan'].map(m=>btn('used_stock','Закупить б/у '+s.models.find(x=>x.id===m).label,`data-model="${m}"`)).join('')}`;
 if(type==='auto_service')html+=`<h3>Закупка полных ремкомплектов за кассовые деньги</h3>${['light','medium','heavy'].map((c,i)=>`<article>${labels[c]} · ${[1500,2000,4000][i]} ₴/шт · остаток ${b.kits[c]} ${field('qty-'+c,1)}${btn('kits_stock','Закупить',`data-class="${c}"`)}</article>`).join('')}`;
 if(type!=='car_factory')html+=`<h3>Тарифы</h3>${(type==='auto_service'?['light','medium','heavy']:s.models.map(m=>m.id)).map(k=>`<label>${labels[k]||s.models.find(m=>m.id===k)?.label}${field('price-'+k,b.prices[k])}${btn('prices','Сохранить',`data-key="${k}"`)}</label>`).join('')}`;
 }
 if(type==='car_dealer'&&b?.owner_id)html+=`<h3>Автомобили в наличии</h3>${s.vehicles.filter(v=>v.business_id===id).map(v=>`<article>${esc(model(v).label)} ${v.used?'б/у':''} · ${money(v.used?20000:b.prices[v.model])}${btn('buy_car','Купить',`data-vehicle="${v.id}"`)}</article>`).join('')}`;
 if(type==='auto_service'&&b?.owner_id)html+=car?`<p>Полный ремонт: ${money(b.prices[model(car).class])}</p>${btn('repair','Отремонтировать полностью',`data-vehicle="${car.id}"`)}`:'<p>Подъедьте на автомобиле к СТО.</p>';
 }
 if(tab==='station')html=`<h3>АЗС · ${esc(id)}</h3><p>Заправляется только подходящее модели топливо, прямо в бак.</p>${car?`<p>${labels[model(car).fuel_type]} · ${money(s.station?.[model(car).fuel_type])}/л · свободно ${(model(car).tank-car.fuel).toFixed(2)} л</p>${field('liters',10)}${btn('refuel','Заправить по тарифу АЗС',`data-vehicle="${car.id}"`)}`:'<p>Сначала сядьте в автомобиль.</p>'}${btn('buy_kit',`Аварийный ремкомплект · ${money(s.station?.kitPrice)}`)}${s.station?.owner===actor?`${field('kitPrice',s.station.kitPrice)}${btn('kit_price','Сохранить цену ремкомплекта')}`:''}`;
 if(tab==='routes')html=`<h3>Заказать транспортную компанию</h3><p>Выберите перевозчика и вознаграждение. Для нефти оплата резервируется со счёта получателя, для партий общей биржи — с личного баланса заказчика.</p>${hubs()}${[...(s.pendingOil||[]).map(d=>({...d,kind:'oil',label:d.product,qty:d.quantity})),...(s.pendingProduction||[]).map(d=>({...d,kind:'production',label:d.product_type,qty:d.quantity}))].map(d=>`<article>${esc(d.label)} × ${d.qty} ${btn('route_create','Создать рейс',`data-kind="${d.kind}" data-delivery="${d.id}"`)}</article>`).join('')}<h3>Рейсы</h3>${s.routes.map(r=>`<article><b>${esc(r.cargo)} × ${r.quantity} · ${money(r.reward)}</b><p>${esc(r.hub?.name||r.hub_id)} · ${esc(r.hub?.city)}</p><p>${esc(r.source?.name||r.source_id)} (${esc(r.source_city)}) → ${esc(r.target?.name||r.target_id)} (${esc(r.target_city)})</p><p>${({open:'Ожидает водителя',pickup:'Ехать на погрузку',unload:'Ехать на выгрузку',done:'Доставлено'})[r.status]||r.status}</p>${r.status==='open'?btn('route_accept','Взять рейс',`data-route="${r.id}"`):r.driver===actor&&['pickup','unload'].includes(r.status)?btn(r.status==='pickup'?'route_load':'route_unload',r.status==='pickup'?'Погрузить на месте':'Разгрузить на месте',`data-route="${r.id}"`):''}</article>`).join('')}`;
 dialog.innerHTML=`<header><h2>Автомобили и перевозки</h2><button data-close>×</button></header><nav>${['garage','routes',...(type?['business']:[])].map(t=>`<button data-tab="${t}">${{garage:'Мои машины',routes:'Логистика',business:'Предприятие'}[t]}</button>`).join('')}<button data-refresh>Обновить</button></nav><p role="status">${esc(busy?'Выполняется…':notice)}</p>${html}`;
 for(const el of dialog.querySelectorAll('[data-field]'))if(drafts.has(el.dataset.field))el.value=drafts.get(el.dataset.field);
 if(focused)[...dialog.querySelectorAll('[data-field]')].find(el=>el.dataset.field===focused)?.focus({preventScroll:true});
 }
 function mapRender(){if(!s)return;const car=current();const m=car&&model(car);window.__MN_VEHICLE_RUNTIME__=car?{id:car.id,canMove:!car.transit_ready&&car.condition>m.stop_condition&&car.fuel>0,speed:.15}:null;
 playerMarker?.classList.toggle('mn-auto-driving',!!car);let carView=playerMarker?.querySelector('.mn-auto-driving-view');if(car&&!carView){carView=document.createElement('span');carView.className='mn-auto-driving-view';playerMarker?.append(carView);}if(carView){if(car)carView.innerHTML=carSvg(car.color);else carView.remove();}hud.textContent=car?`${m.label} · ${Number(car.fuel).toFixed(1)} л · ${Math.floor(car.condition)}/${m.max_condition} · F выйти · H АЗС`:'';
 layer.innerHTML=s.vehicles.filter(v=>v.city_id===cityId&&(!v.driving||v.owner_id!==actor)).map(v=>`<div class="mn-auto-car" style="left:${Number(v.x)}%;top:${Number(v.y)}%;color:${esc(v.color)}">${carSvg(v.color)}<b>${esc(model(v)?.label)}</b></div>`).join('');
 const r=s.routes.find(r=>r.driver===actor&&['pickup','unload'].includes(r.status));if(r){const pt=r.status==='pickup'?r.source:r.target;if(pt?.city===cityId)layer.innerHTML+=`<div class="mn-auto-marker" style="left:${Number(pt.x)}%;top:${Number(pt.y)}%">${r.status==='pickup'?'📦 Погрузка':'🏁 Выгрузка'}</div>`;else hud.textContent+=` · Цель: ${pt?.city||'другой город'}`;}
 }
 async function refresh(){const next=await vehicleRequest(cityId,id);if(destroyed)return;s=next;mapRender();if(dialog.open)render();}
 async function act(a,data={}){if(busy)return;busy=true;render();const signature=JSON.stringify([id,a,data]);const request=retry?.signature===signature?retry.request:crypto.randomUUID();retry={signature,request};try{s=await vehicleRequest(cityId,id,a,data,request);retry=null;notice='✓ Выполнено';window.dispatchEvent(new CustomEvent('mn:player-balance-refresh'));mapRender();if(a==='arrive'){const c=current();if(c){state.city=c.city_id;state.cityId=c.city_id;state.player={...state.player,city:c.city_id};save();location.reload();}}}catch(e){notice=vehicleError(e);}finally{busy=false;if(!destroyed)render();}}
 async function open(nextId='',nextType='',nextTab='garage'){id=nextId;type=nextType;tab=nextTab;notice='';await refresh();if(!destroyed){render();if(!dialog.open)dialog.showModal();}}
 launch.onclick=()=>open().catch(e=>{hud.textContent=vehicleError(e);});
 const onOpen=e=>{const o=e.detail?.object;if(o)open(String(o.id),o.type==='marker'?o.payload?.jobType:o.type,'business').catch(e=>hud.textContent=vehicleError(e));};
 const onRoutes=()=>open('','','routes').catch(e=>hud.textContent=vehicleError(e));
 window.addEventListener('mn:auto-object-action',onOpen);window.addEventListener('mn:auto-routes-open',onRoutes);
 dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('keydown',e=>e.stopPropagation());dialog.addEventListener('keyup',e=>e.stopPropagation());
 dialog.onclick=async e=>{const b=e.target.closest('button');if(!b||b.disabled||busy)return;if(b.hasAttribute('data-close')){dialog.close();return;}if(b.dataset.tab){tab=b.dataset.tab;render();return;}if(b.hasAttribute('data-refresh')){await refresh().catch(e=>{notice=vehicleError(e);render();});return;}const a=b.dataset.action;if(!a)return;let data={vehicle:b.dataset.vehicle,model:b.dataset.model};
 if(['deposit','withdraw'].includes(a))data={amount:Number(val('amount'))};if(a==='prices')data={key:b.dataset.key,price:Number(val('price-'+b.dataset.key))};if(a==='kits_stock')data={class:b.dataset.class,quantity:Number(val('qty-'+b.dataset.class))};
 if(['components_buy','car_order','route_create'].includes(a))data={...data,offer:b.dataset.offer,hub:val('hub'),reward:Number(val('reward')),kind:b.dataset.kind,delivery:b.dataset.delivery};
 if(a==='enter')data={...data,x:playerPosition.x,y:playerPosition.y};if(a==='paint')data.color=val('color-'+data.vehicle);if(a==='reserve_refuel')data.liters=Number(val('reserve-'+data.vehicle));if(a==='refuel'){data.liters=Number(val('liters'));data.unitPrice=Number(s.station?.[model(current()).fuel_type]);}if(a==='buy_kit')data={unitPrice:Number(s.station?.kitPrice)};if(a==='kit_price')data={price:Number(val('kitPrice'))};if(a==='travel')data.city=val('city');
 if(a.startsWith('route_')&&a!=='route_create')data={route:b.dataset.route};
 if(['route_load','route_unload'].includes(a)){const r=s.routes.find(r=>r.id===data.route);const pt=a==='route_load'?r.source:r.target;const c=current();if(!c||pt?.city!==cityId||Math.hypot(playerPosition.x-pt.x,playerPosition.y-pt.y)>2){notice='Подъедьте на служебной машине к метке.';render();return;}busy=true;dialog.close();let result;try{result=await playCargoTransferMiniGame({direction:a==='route_load'?'factory_to_vehicle':'vehicle_to_store',productType:['crude','petrol','petrol92','diesel'].includes(r.cargo)?'oil_'+r.cargo:r.cargo,quantity:r.quantity});}finally{busy=false;if(!destroyed)dialog.showModal();}if(!result?.success)return;}
 await act(a,data);};
 const honk=()=>{try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),gain=ctx.createGain();gain.gain.value=.06;gain.connect(ctx.destination);for(const frequency of [370,490]){const osc=ctx.createOscillator();osc.type='square';osc.frequency.value=frequency;osc.connect(gain);osc.start();osc.stop(ctx.currentTime+.18);}setTimeout(()=>ctx.close(),250);}catch{}};
 const key=async e=>{if(e.repeat||dialog.open||document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName)||busy||!s)return;try{if(e.code==='KeyF'){e.preventDefault();const car=current()||s.vehicles.filter(v=>v.owner_id===actor&&v.city_id===cityId).sort((a,b)=>Math.hypot(a.x-playerPosition.x,a.y-playerPosition.y)-Math.hypot(b.x-playerPosition.x,b.y-playerPosition.y))[0];if(car)await act(car.driving?'exit':'enter',{vehicle:car.id,x:playerPosition.x,y:playerPosition.y});}if(e.code==='KeyH'&&current()){e.preventDefault();honk();objects=await getMapObjects(cityId);const station=objects.filter(o=>(o.type==='fuel_station'||o.payload?.jobType==='fuel_station')&&Math.hypot(o.x-playerPosition.x,o.y-playerPosition.y)<=2).sort((a,b)=>Math.hypot(a.x-playerPosition.x,a.y-playerPosition.y)-Math.hypot(b.x-playerPosition.x,b.y-playerPosition.y))[0];if(station)await open(String(station.id),'','station');else hud.textContent='Подъедьте к выбранной АЗС.';}}catch(err){hud.textContent=vehicleError(err);}};
 window.addEventListener('keydown',key);
 const timer=setInterval(async()=>{if(destroyed||busy||moving||!s)return;const c=current();if(!c||c.city_id!==cityId||c.transit_ready)return;moving=true;try{const result=await vehicleRequest(cityId,'','move',{vehicle:c.id,x:playerPosition.x,y:playerPosition.y});if(result.moved){Object.assign(c,result.moved);mapRender();}}catch(e){window.dispatchEvent(new CustomEvent('mn:player-teleported',{detail:{x:c.x,y:c.y}}));hud.textContent=vehicleError(e);}finally{moving=false;}},1500);
 const poll=setInterval(()=>{if(!busy&&!moving&&dialog.open)refresh().catch(()=>{});},5000);
 refresh().then(()=>{const c=current();if(c?.city_id===cityId)window.dispatchEvent(new CustomEvent('mn:player-teleported',{detail:{x:c.x,y:c.y}}));}).catch(()=>{});
 return()=>{destroyed=true;clearInterval(timer);clearInterval(poll);window.__MN_VEHICLE_RUNTIME__=null;window.removeEventListener('keydown',key);window.removeEventListener('mn:auto-object-action',onOpen);window.removeEventListener('mn:auto-routes-open',onRoutes);dialog.remove();launch.remove();hud.remove();layer.remove();playerMarker?.classList.remove('mn-auto-driving');};
}
