import './productionMarket.css';
import { state, save } from '../state.js';
import { loadRawMarket, sellToFactory, loadProductionExchange, createFactoryOffer, createStoreRequest, acceptStoreRequest, buyFactoryOffer, getFactoryError } from '../factory/factoryApi.js';

const PRODUCTS = { grocery_apple_juice:['🧃','Яблочный сок'], grocery_orange_juice:['🥤','Апельсиновый сок'], grocery_fruit_puree:['🥫','Фруктовое пюре'] };
const CROPS = { farm_apple:['🍎','Яблоки'], farm_orange:['🍊','Апельсины'], farm_wheat:['🌾','Пшеница'], farm_corn:['🌽','Кукуруза'] };
const esc = (v) => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money = (v) => `${Math.max(0,Math.round(Number(v)||0)).toLocaleString('ru-RU')} ₴`;
const toast = (message,type='info') => window.dispatchEvent(new CustomEvent('mn:toast',{detail:{message,type}}));

function shell() { return `<div class="mn-production-shortcuts"><button data-raw-market-open><b>O</b><span>Продать сырьё</span></button><button data-exchange-open><b>M</b><span>Биржа продукции</span></button></div><div class="mn-production-market" data-production-market hidden><button class="mn-production-backdrop" data-market-close></button><section><header><div><small data-market-eyebrow>РЫНОК</small><h2 data-market-title>Производственная экономика</h2></div><button data-market-close>×</button></header><main data-market-content></main></section></div>`; }

function rawMarkup(data) {
  const offers = data.offers || [];
  return `<div class="mn-market-hero"><i>🌾</i><span><strong>Продажа урожая производствам</strong><small>Выберите продукт, завод и город. Цена и доступный объём показаны до продажи.</small></span></div><div class="mn-market-form"><label><span>Что продаём</span><select data-raw-item>${Object.entries(CROPS).map(([id,[icon,label]])=>`<option value="${id}">${icon} ${label}</option>`).join('')}</select></label><label><span>Количество</span><input type="number" min="1" value="10" data-raw-qty></label></div><div class="mn-market-list" data-raw-offers>${offers.length ? offers.map((o)=>`<article data-item="${esc(o.itemType)}"><i>${CROPS[o.itemType]?.[0]||'📦'}</i><span><strong>${esc(o.factoryName)}</strong><small>${esc(o.cityName||o.cityId)} · принимает до ${Number(o.capacityLeft)} ед.</small></span><b>${money(o.unitPrice)} / ед.</b><button data-raw-sell="${esc(o.factoryId)}" data-city="${esc(o.cityId)}" data-item="${esc(o.itemType)}">Продать</button></article>`).join('') : '<p>Заводы пока не выставили цены закупки.</p>'}</div>`;
}

function exchangeMarkup(data) {
  const factories=data.myFactories||[], stores=data.myStores||[], offers=data.offers||[], requests=data.requests||[];
  return `<div class="mn-market-tabs"><button class="is-active" data-ex-tab="offers">Предложения заводов</button><button data-ex-tab="requests">Заявки магазинов</button><button data-ex-tab="create">Разместить офер</button></div><div data-ex-page="offers"><div class="mn-market-list">${offers.length?offers.map((o)=>`<article><i>${PRODUCTS[o.productType]?.[0]||'📦'}</i><span><strong>${PRODUCTS[o.productType]?.[1]||esc(o.productType)}</strong><small>${esc(o.factoryName)} · ${esc(o.cityName||o.cityId)} · ${Number(o.quantity)} ед.</small></span><b>${money(o.unitPrice)} / ед.</b>${stores.length?`<select data-offer-store="${esc(o.id)}">${stores.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select><button data-offer-buy="${esc(o.id)}">Закупить</button>`:''}</article>`).join(''):'<p>Активных предложений заводов пока нет.</p>'}</div></div><div data-ex-page="requests" hidden><div class="mn-market-list">${requests.length?requests.map((r)=>`<article><i>${PRODUCTS[r.productType]?.[0]||'📦'}</i><span><strong>${PRODUCTS[r.productType]?.[1]||esc(r.productType)}</strong><small>${esc(r.storeName)} · нужно ${Number(r.quantity)} ед.</small></span><b>${money(r.unitPrice)} / ед.</b>${factories.length?`<select data-request-factory="${esc(r.id)}">${factories.map(f=>`<option value="${esc(f.id)}" data-city="${esc(f.cityId)}">${esc(f.name)}</option>`).join('')}</select><button data-request-accept="${esc(r.id)}">Взять заказ</button>`:''}</article>`).join(''):'<p>Магазины пока ничего не запрашивают.</p>'}</div></div><div data-ex-page="create" hidden><div class="mn-market-create-grid"><article><h3>Офер от производства</h3>${factories.length?`<select data-create-factory>${factories.map(f=>`<option value="${esc(f.id)}" data-city="${esc(f.cityId)}">${esc(f.name)}</option>`).join('')}</select><select data-create-factory-product>${Object.entries(PRODUCTS).map(([id,[icon,label]])=>`<option value="${id}">${icon} ${label}</option>`).join('')}</select><input type="number" min="1" value="10" placeholder="Количество" data-create-factory-qty><input type="number" min="1" value="50" placeholder="Цена за единицу" data-create-factory-price><button data-create-factory-offer>Выставить товар со склада</button>`:'<p>У вас нет производственного предприятия.</p>'}</article><article><h3>Заявка от магазина</h3>${stores.length?`<select data-create-store>${stores.map(s=>`<option value="${esc(s.id)}" data-city="${esc(s.cityId)}">${esc(s.name)}</option>`).join('')}</select><select data-create-store-product>${Object.entries(PRODUCTS).map(([id,[icon,label]])=>`<option value="${id}">${icon} ${label}</option>`).join('')}</select><input type="number" min="1" value="50" placeholder="Необходимое количество" data-create-store-qty><input type="number" min="1" value="55" placeholder="Цена за единицу" data-create-store-price><button data-create-store-request>Разместить заявку</button>`:'<p>У вас нет продуктового магазина.</p>'}</article></div></div>`;
}

export function enableProductionMarketFeature({root}) {
  root.insertAdjacentHTML('beforeend',shell()); const modal=root.querySelector('[data-production-market]'), content=modal.querySelector('[data-market-content]'); let mode='',data=null,busy=false;
  const open=async(next)=>{if(busy)return;busy=true;mode=next;modal.hidden=false;content.innerHTML='<div class="mn-market-loading">Загружаем предложения…</div>';try{data=next==='raw'?await loadRawMarket():await loadProductionExchange();content.innerHTML=next==='raw'?rawMarkup(data):exchangeMarkup(data);modal.querySelector('[data-market-title]').textContent=next==='raw'?'Продать сырьё':'Биржа готовой продукции';modal.querySelector('[data-market-eyebrow]').textContent=next==='raw'?'КЛАВИША O':'КЛАВИША M';}catch(e){content.innerHTML=`<div class="mn-market-error">${esc(getFactoryError(e))}</div>`;}finally{busy=false;}};
  const close=()=>{modal.hidden=true;}; root.querySelector('[data-raw-market-open]').onclick=()=>open('raw');root.querySelector('[data-exchange-open]').onclick=()=>open('exchange');modal.querySelectorAll('[data-market-close]').forEach(b=>b.onclick=close);
  const key=(e)=>{if(e.repeat||/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName||''))return;if(e.code==='KeyO'){e.preventDefault();void open('raw');}if(e.code==='KeyM'){e.preventDefault();void open('exchange');}if(e.key==='Escape'&&!modal.hidden)close();};window.addEventListener('keydown',key,true);
  content.addEventListener('change',(e)=>{if(e.target.matches('[data-raw-item]'))content.querySelectorAll('[data-raw-offers] article').forEach(a=>a.hidden=a.dataset.item!==e.target.value);});
  content.addEventListener('click',async(e)=>{const t=e.target;if(busy)return;const tab=t.closest('[data-ex-tab]');if(tab){content.querySelectorAll('[data-ex-tab]').forEach(b=>b.classList.toggle('is-active',b===tab));content.querySelectorAll('[data-ex-page]').forEach(p=>p.hidden=p.dataset.exPage!==tab.dataset.exTab);return;}let task=null,msg='';const sell=t.closest('[data-raw-sell]');if(sell){task=()=>sellToFactory(sell.dataset.rawSell,sell.dataset.city,sell.dataset.item,Number(content.querySelector('[data-raw-qty]').value));msg='Сырьё принято заводом.';}const buy=t.closest('[data-offer-buy]');if(buy){task=()=>buyFactoryOffer(buy.dataset.offerBuy,content.querySelector(`[data-offer-store="${buy.dataset.offerBuy}"]`).value);msg='Товар закуплен на склад магазина.';}const accept=t.closest('[data-request-accept]');if(accept){const select=content.querySelector(`[data-request-factory="${accept.dataset.requestAccept}"]`),opt=select.selectedOptions[0];task=()=>acceptStoreRequest(accept.dataset.requestAccept,select.value,opt.dataset.city);msg='Завод принял заказ магазина.';}if(t.closest('[data-create-factory-offer]')){const s=content.querySelector('[data-create-factory]'),opt=s.selectedOptions[0];task=()=>createFactoryOffer({factoryId:s.value,cityId:opt.dataset.city,productType:content.querySelector('[data-create-factory-product]').value,quantity:Number(content.querySelector('[data-create-factory-qty]').value),unitPrice:Number(content.querySelector('[data-create-factory-price]').value)});msg='Предложение завода опубликовано.';}if(t.closest('[data-create-store-request]')){const s=content.querySelector('[data-create-store]'),opt=s.selectedOptions[0];task=()=>createStoreRequest({businessId:s.value,cityId:opt.dataset.city,productType:content.querySelector('[data-create-store-product]').value,quantity:Number(content.querySelector('[data-create-store-qty]').value),unitPrice:Number(content.querySelector('[data-create-store-price]').value)});msg='Заявка магазина опубликована.';}if(!task)return;busy=true;try{const result=await task();const balance=Number(result?.playerBalance);if(Number.isFinite(balance)){state.player={...(state.player||{}),balance};save();window.dispatchEvent(new CustomEvent('mn:player-balance-changed',{detail:{balance,source:'production_market'}}));}toast(msg,'success');busy=false;await open(mode);}catch(err){toast(getFactoryError(err),'error');}finally{busy=false;}});
  return()=>{window.removeEventListener('keydown',key,true);modal.remove();root.querySelector('.mn-production-shortcuts')?.remove();};
}
