import { playIndustryMiniGame } from '../industry/industryMiniGames.js';
import { depositBusinessFunds, withdrawBusinessProfit } from '../business/businessApi.js';
import { state, save } from '../state.js';
import { acceptLogisticsContract, buyLogisticsVehicle, completeLogisticsContract, createLogisticsContract, loadLogisticsSnapshot, logisticsError } from './logisticsApi.js';
import './logistics.css';
import './logisticsFleet.css';

const esc = (v) => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const money = (v) => `${Math.max(0,Math.round(Number(v)||0)).toLocaleString('ru-RU')} ₴`;
const toast = (message,type='info') => window.dispatchEvent(new CustomEvent('mn:toast',{detail:{message,type}}));
const idOf = (o) => String(o?.id || o?.mapObjectId || o?.payload?.mapObjectId || '');

function contractCard(c, ownActive) {
  const assigned = c.status === 'assigned';
  const role = c.roleId === 'loader' ? 'Грузчик' : 'Водитель';
  return `<article class="mn-logistics-contract is-${esc(c.status)}"><header><span><small>${esc(c.cargoLabel||c.cargoType)}</small><strong>${Number(c.quantity||0)} ед. · ${esc(c.destination||'По городу')}</strong></span><b>${money(c.payout)}</b></header><div><span>Работа: ${role}</span><span>${assigned ? `Исполнитель: ${esc(c.workerName||'занят')}` : 'Свободная заявка'}</span></div>${c.canComplete?`<button data-logistics-complete="${esc(c.id)}" data-role="${esc(c.roleId)}">Выполнить этап</button>`:c.canAccept?`<button data-logistics-accept="${esc(c.id)}" data-role="${esc(c.roleId)}"${ownActive?' disabled':''}>Принять работу</button>`:''}</article>`;
}

function markup(s) {
  const fleet=(s.fleet||[]), contracts=(s.contracts||[]), active=contracts.some(c=>c.isMine&&c.status==='assigned');
  const totalVehicles=fleet.reduce((sum,v)=>sum+Number(v.quantity||0),0);
  const totalCapacity=fleet.reduce((sum,v)=>sum+Number(v.quantity||0)*Number(v.capacity||0),0);
  const activeRoutes=contracts.filter(c=>c.status==='assigned').length;
  return `<header class="mn-logistics-head"><span><small>${esc(s.cityId)} · ТРАНСПОРТНАЯ КОМПАНИЯ</small><strong>🚚 ${esc(s.name||'Логистический центр')}</strong><em>${esc(s.roleLabel||'Посетитель')} · счёт ${s.canManage?money(s.cashBalance):'скрыт'}</em></span><button data-logistics-close>×</button></header><nav><button class="is-active" data-logistics-tab="board">Диспетчерская</button><button data-logistics-tab="fleet">Автопарк</button><button data-logistics-tab="manage">Управление</button></nav><main>
  <section data-logistics-page="board"><div class="mn-logistics-stats"><article><small>Свободные заявки</small><strong>${contracts.filter(c=>c.status==='open').length}</strong></article><article><small>Активные рейсы</small><strong>${contracts.filter(c=>c.status==='assigned').length}</strong></article><article><small>Выполнено</small><strong>${Number(s.completedCount||0)}</strong></article></div><div class="mn-logistics-contracts">${contracts.length?contracts.map(c=>contractCard(c,active)).join(''):'<p>Заявок пока нет. Владелец может создать первую перевозку.</p>'}</div></section>
  <section data-logistics-page="fleet" hidden><div class="mn-fleet-title"><span><small>ТРАНСПОРТНЫЙ ОТДЕЛ</small><h3>Автопарк предприятия</h3><p>Транспорт определяет доступные рейсы и общую грузоподъёмность компании.</p></span>${s.isOwner?`<b>Бюджет автопарка<br><strong>${money(s.cashBalance)}</strong></b>`:''}</div><div class="mn-fleet-summary"><article><i>🚚</i><span><small>Всего транспорта</small><strong>${totalVehicles} ед.</strong></span></article><article><i>📦</i><span><small>Общая вместимость</small><strong>${totalCapacity} ед.</strong></span></article><article><i>🛣️</i><span><small>Сейчас в работе</small><strong>${activeRoutes} рейс.</strong></span></article></div><h3>Транспорт компании</h3><div class="mn-logistics-fleet">${fleet.map(v=>`<article class="mn-fleet-card"><div class="mn-fleet-icon">${v.icon}</div><span><small>${v.type==='truck'?'ТЯЖЁЛЫЙ ТРАНСПОРТ':'ГОРОДСКАЯ ДОСТАВКА'}</small><strong>${esc(v.label)}</strong><em>До ${v.capacity} единиц груза за один рейс</em></span><div><b>${v.quantity}</b><small>в парке</small><mark>${activeRoutes?'Часть машин в рейсе':'Все свободны'}</mark></div></article>`).join('')||'<div class="mn-fleet-empty"><i>🅿️</i><strong>Автопарк пуст</strong><span>Приобретите первый автомобиль, чтобы открыть работу водителя.</span></div>'}</div>${s.isOwner?`<h3>Каталог транспорта</h3><div class="mn-logistics-buy"><article><i>🚐</i><span><strong>Городской фургон</strong><small>60 ед. · малые и срочные поставки</small></span><b>180 000 ₴</b><button data-logistics-vehicle="van"${Number(s.cashBalance)<180000?' disabled':''}>Приобрести</button></article><article><i>🚛</i><span><strong>Грузовой автомобиль</strong><small>200 ед. · крупные промышленные партии</small></span><b>420 000 ₴</b><button data-logistics-vehicle="truck"${Number(s.cashBalance)<420000?' disabled':''}>Приобрести</button></article></div>`:''}</section>
  <section data-logistics-page="manage" hidden>${s.isOwner?`<h3>Финансы предприятия</h3><div class="mn-logistics-finance"><strong>${money(s.cashBalance)}</strong><input type="number" min="1" data-logistics-money placeholder="Сумма"><button data-logistics-deposit>Пополнить со своего баланса</button><button data-logistics-withdraw${Number(s.cashBalance)>0?'':' disabled'}>Снять на личный баланс</button></div><h3>Новая заявка</h3><div class="mn-logistics-form"><input data-logistics-cargo placeholder="Тип груза" maxlength="48"><input type="number" min="1" value="20" data-logistics-quantity><input data-logistics-destination placeholder="Куда доставить" maxlength="64"><input type="number" min="10" value="250" data-logistics-payout><select data-logistics-role><option value="driver">Водитель</option><option value="loader">Грузчик</option></select><button data-logistics-create>Опубликовать заявку</button></div><p>Вознаграждение выплачивается со счёта бизнеса после выполнения работы.</p>`:'<p>Управление доступно владельцу.</p>'}</section></main>`;
}

export function enableLogisticsFeature({root}) {
  root.insertAdjacentHTML('beforeend','<div class="mn-logistics-modal" data-logistics-modal hidden><section class="mn-logistics-panel" data-logistics-content></section></div>');
  const modal=root.querySelector('[data-logistics-modal]'), content=modal.querySelector('[data-logistics-content]');
  let businessId='', snapshot=null, busy=false;
  const render=()=>{content.innerHTML=markup(snapshot);content.querySelectorAll('[data-logistics-tab]').forEach(b=>b.onclick=()=>{content.querySelectorAll('[data-logistics-tab]').forEach(x=>x.classList.toggle('is-active',x===b));content.querySelectorAll('[data-logistics-page]').forEach(p=>p.hidden=p.dataset.logisticsPage!==b.dataset.logisticsTab)});};
  const refresh=async()=>{snapshot=await loadLogisticsSnapshot(businessId);render()};
  const run=async(fn)=>{if(busy)return;busy=true;modal.classList.add('is-busy');try{await fn();await refresh()}catch(e){toast(logisticsError(e),'error')}finally{busy=false;modal.classList.remove('is-busy')}};
  const open=e=>{businessId=String(e.detail?.businessId||idOf(e.detail?.object));modal.hidden=false;void run(refresh)};
  const syncBalance=result=>{const balance=Number(result?.playerBalance);if(!Number.isFinite(balance))return;state.player={...(state.player||{}),balance};save();window.dispatchEvent(new CustomEvent('mn:player-balance-changed',{detail:{balance,source:'logistics_finance',result}}));};
  content.onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.matches('[data-logistics-close]'))modal.hidden=true;if(b.dataset.logisticsAccept)void run(()=>acceptLogisticsContract(businessId,b.dataset.logisticsAccept,b.dataset.role));if(b.dataset.logisticsComplete)void run(async()=>{const game=b.dataset.role==='loader'?'loader':'forklift',result=await playIndustryMiniGame(game);if(!result.cancelled)await completeLogisticsContract(businessId,b.dataset.logisticsComplete,result)});if(b.dataset.logisticsVehicle)void run(()=>buyLogisticsVehicle(businessId,b.dataset.logisticsVehicle));if(b.matches('[data-logistics-deposit]'))void run(async()=>syncBalance(await depositBusinessFunds({businessId,amount:Number(content.querySelector('[data-logistics-money]').value)})));if(b.matches('[data-logistics-withdraw]'))void run(async()=>syncBalance(await withdrawBusinessProfit({businessId,amount:Number(content.querySelector('[data-logistics-money]').value)})));if(b.matches('[data-logistics-create]'))void run(()=>createLogisticsContract({businessId,cargoType:content.querySelector('[data-logistics-cargo]').value,quantity:Number(content.querySelector('[data-logistics-quantity]').value),destination:content.querySelector('[data-logistics-destination]').value,payout:Number(content.querySelector('[data-logistics-payout]').value),roleId:content.querySelector('[data-logistics-role]').value}));};
  window.addEventListener('mn:logistics-open',open);
  return()=>{window.removeEventListener('mn:logistics-open',open);modal.remove()};
}
