-- Больничный склад, должности, продажи, статистика и лечение препаратами.
-- По умолчанию сотрудники из hospital_employees имеют доступ согласно своему рангу.

alter table public.players
  alter column health type numeric(5,1) using health::numeric(5,1),
  alter column health set default 100;

alter table public.player_positions
  alter column health type numeric(5,1) using health::numeric(5,1),
  alter column health set default 100;

create table if not exists public.hospital_settings (
  hospital_id text primary key,
  employee_access_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.hospital_settings
  alter column employee_access_enabled set default true;

create table if not exists public.hospital_item_catalog (
  hospital_id text not null references public.hospital_settings(hospital_id) on delete cascade,
  item_type text not null check (item_type in ('food', 'medicine_light', 'medicine_strong', 'medicine_resuscitation')),
  label text not null,
  icon text not null default '□',
  heal_per_tick numeric(6,2) not null default 0 check (heal_per_tick >= 0),
  tick_seconds integer not null default 0 check (tick_seconds >= 0),
  duration_seconds integer not null default 0 check (duration_seconds between 0 and 3600),
  min_health numeric(5,1) not null default 0 check (min_health between 0 and 100),
  max_health numeric(5,1) not null default 100 check (max_health between 0 and 100),
  min_food numeric(5,1) not null default 0 check (min_food between 0 and 100),
  min_take_rank integer not null default 3 check (min_take_rank between 1 and 3),
  min_treat_rank integer not null default 3 check (min_treat_rank between 1 and 3),
  min_sell_rank integer not null default 3 check (min_sell_rank between 1 and 3),
  sale_price bigint not null default 0 check (sale_price >= 0),
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (hospital_id, item_type),
  check (min_health < max_health or item_type = 'food')
);

create table if not exists public.hospital_warehouse_stock (
  hospital_id text not null,
  item_type text not null,
  quantity bigint not null default 0 check (quantity >= 0),
  updated_by_tg_id text,
  updated_at timestamptz not null default now(),
  primary key (hospital_id, item_type),
  foreign key (hospital_id, item_type)
    references public.hospital_item_catalog(hospital_id, item_type) on delete cascade
);

create table if not exists public.hospital_employees (
  hospital_id text not null references public.hospital_settings(hospital_id) on delete cascade,
  employee_tg_id text not null,
  rank text not null check (rank in ('junior', 'middle', 'senior')),
  appointed_by_tg_id text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (hospital_id, employee_tg_id)
);

create table if not exists public.hospital_employee_inventory (
  hospital_id text not null,
  employee_tg_id text not null,
  item_type text not null,
  quantity bigint not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now(),
  primary key (hospital_id, employee_tg_id, item_type),
  foreign key (hospital_id, item_type)
    references public.hospital_item_catalog(hospital_id, item_type) on delete cascade
);

create table if not exists public.hospital_supply_orders (
  id bigint generated by default as identity primary key,
  hospital_id text not null references public.hospital_settings(hospital_id) on delete cascade,
  item_type text not null default 'food' check (item_type = 'food'),
  quantity bigint not null check (quantity > 0),
  status text not null default 'pending' check (status in ('pending', 'delivered', 'cancelled')),
  ordered_by_tg_id text not null,
  completed_by_tg_id text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.hospital_stock_movements (
  id bigint generated by default as identity primary key,
  hospital_id text not null references public.hospital_settings(hospital_id) on delete cascade,
  actor_tg_id text not null,
  target_tg_id text,
  item_type text not null,
  movement_type text not null check (movement_type in ('refill', 'take', 'treat', 'sell', 'order_food')),
  quantity bigint not null check (quantity > 0),
  balance_after bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.hospital_employee_stats (
  hospital_id text not null references public.hospital_settings(hospital_id) on delete cascade,
  employee_tg_id text not null,
  players_treated bigint not null default 0 check (players_treated >= 0),
  medicines_given bigint not null default 0 check (medicines_given >= 0),
  medicines_sold bigint not null default 0 check (medicines_sold >= 0),
  health_restored numeric(12,2) not null default 0 check (health_restored >= 0),
  revenue bigint not null default 0 check (revenue >= 0),
  updated_at timestamptz not null default now(),
  primary key (hospital_id, employee_tg_id)
);

create table if not exists public.hospital_finances (
  hospital_id text primary key references public.hospital_settings(hospital_id) on delete cascade,
  balance bigint not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_medical_inventory (
  player_tg_id text not null,
  item_type text not null check (item_type in ('medicine_light', 'medicine_strong', 'medicine_resuscitation')),
  quantity bigint not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now(),
  primary key (player_tg_id, item_type)
);

create table if not exists public.hospital_treatment_effects (
  id bigint generated by default as identity primary key,
  hospital_id text not null references public.hospital_settings(hospital_id) on delete cascade,
  patient_tg_id text not null,
  clinician_tg_id text not null,
  medicine_type text not null check (medicine_type in ('medicine_light', 'medicine_strong', 'medicine_resuscitation')),
  heal_per_tick numeric(6,2) not null check (heal_per_tick > 0),
  tick_seconds integer not null check (tick_seconds > 0),
  started_at timestamptz not null default now(),
  last_processed_at timestamptz not null default now(),
  expires_at timestamptz not null,
  status text not null default 'active' check (status in ('active', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);

create unique index if not exists hospital_one_active_treatment_per_patient
  on public.hospital_treatment_effects(patient_tg_id)
  where status = 'active';

create index if not exists hospital_employee_stats_order_idx
  on public.hospital_employee_stats(hospital_id, players_treated desc, medicines_sold desc);

create index if not exists hospital_stock_movements_history_idx
  on public.hospital_stock_movements(hospital_id, created_at desc);

alter table public.hospital_settings enable row level security;
alter table public.hospital_item_catalog enable row level security;
alter table public.hospital_warehouse_stock enable row level security;
alter table public.hospital_employees enable row level security;
alter table public.hospital_employee_inventory enable row level security;
alter table public.hospital_supply_orders enable row level security;
alter table public.hospital_stock_movements enable row level security;
alter table public.hospital_employee_stats enable row level security;
alter table public.hospital_finances enable row level security;
alter table public.player_medical_inventory enable row level security;
alter table public.hospital_treatment_effects enable row level security;

create or replace function public.hospital_rank_level(p_rank text)
returns integer
language sql
immutable
as $$
  select case lower(coalesce(p_rank, ''))
    when 'junior' then 1
    when 'middle' then 2
    when 'senior' then 3
    when 'admin' then 4
    else 0
  end;
$$;

create or replace function public.hospital_player_is_admin(p_tg_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select p.is_admin is true
    from public.players p
    where p.tg_id::text = trim(coalesce(p_tg_id, ''))
    limit 1
  ), false);
$$;

create or replace function public.hospital_resolve_player_tg_id(p_target text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.tg_id::text
  from public.players p
  where p.tg_id::text = trim(coalesce(p_target, ''))
     or lower(p.nickname::text) = lower(trim(coalesce(p_target, '')))
  order by case when p.tg_id::text = trim(coalesce(p_target, '')) then 0 else 1 end
  limit 1;
$$;

create or replace function public.hospital_ensure(p_hospital_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hospital_id text := trim(coalesce(p_hospital_id, ''));
begin
  if v_hospital_id = '' or length(v_hospital_id) > 160 then
    raise exception 'HOSPITAL_ID_INVALID';
  end if;

  insert into public.hospital_settings(hospital_id)
  values (v_hospital_id)
  on conflict (hospital_id) do nothing;

  insert into public.hospital_item_catalog(
    hospital_id, item_type, label, icon, heal_per_tick, tick_seconds,
    duration_seconds, min_health, max_health, min_food,
    min_take_rank, min_treat_rank, min_sell_rank, sale_price
  ) values
    (v_hospital_id, 'food', 'Продукты', '🍱', 0, 0, 0, 0, 100, 0, 2, 3, 3, 0),
    (v_hospital_id, 'medicine_light', 'Простые таблетки', '💊', 0.5, 10, 60, 50, 100, 40, 1, 1, 2, 0),
    (v_hospital_id, 'medicine_strong', 'Сильные таблетки', '💉', 2, 5, 60, 15, 50, 40, 3, 3, 3, 0),
    (v_hospital_id, 'medicine_resuscitation', 'Реанимационные таблетки', '⚕', 7.5, 2, 60, 0, 15, 40, 3, 3, 3, 0)
  on conflict (hospital_id, item_type) do nothing;

  insert into public.hospital_warehouse_stock(hospital_id, item_type, quantity)
  select v_hospital_id, c.item_type, 0
  from public.hospital_item_catalog c
  where c.hospital_id = v_hospital_id
  on conflict (hospital_id, item_type) do nothing;

  insert into public.hospital_finances(hospital_id, balance)
  values (v_hospital_id, 0)
  on conflict (hospital_id) do nothing;
end;
$$;

create or replace function public.hospital_get_actor_access(p_hospital_id text, p_actor_tg_id text)
returns table(is_admin boolean, employee_access_enabled boolean, rank text, rank_level integer, allowed boolean)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.hospital_ensure(p_hospital_id);

  return query
  select
    public.hospital_player_is_admin(p_actor_tg_id),
    hs.employee_access_enabled,
    case
      when public.hospital_player_is_admin(p_actor_tg_id) then 'admin'
      else he.rank
    end,
    case
      when public.hospital_player_is_admin(p_actor_tg_id) then 4
      else public.hospital_rank_level(he.rank)
    end,
    public.hospital_player_is_admin(p_actor_tg_id)
      or (hs.employee_access_enabled and he.active is true and he.rank is not null)
  from public.hospital_settings hs
  left join public.hospital_employees he
    on he.hospital_id = hs.hospital_id
   and he.employee_tg_id = trim(coalesce(p_actor_tg_id, ''))
   and he.active is true
  where hs.hospital_id = trim(coalesce(p_hospital_id, ''));
end;
$$;

create or replace function public.hospital_get_context(p_hospital_id text, p_actor_tg_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_access record;
  v_items jsonb;
begin
  select * into v_access
  from public.hospital_get_actor_access(p_hospital_id, p_actor_tg_id);

  select coalesce(jsonb_agg(jsonb_build_object(
    'itemType', c.item_type,
    'label', c.label,
    'icon', c.icon,
    'healPerTick', c.heal_per_tick,
    'tickSeconds', c.tick_seconds,
    'durationSeconds', c.duration_seconds,
    'minHealth', c.min_health,
    'maxHealth', c.max_health,
    'minFood', c.min_food,
    'salePrice', c.sale_price,
    'warehouseQuantity', coalesce(s.quantity, 0),
    'personalQuantity', coalesce(i.quantity, 0)
  ) order by case c.item_type
    when 'food' then 1
    when 'medicine_light' then 2
    when 'medicine_strong' then 3
    else 4
  end), '[]'::jsonb)
  into v_items
  from public.hospital_item_catalog c
  left join public.hospital_warehouse_stock s
    on s.hospital_id = c.hospital_id and s.item_type = c.item_type
  left join public.hospital_employee_inventory i
    on i.hospital_id = c.hospital_id
   and i.item_type = c.item_type
   and i.employee_tg_id = trim(coalesce(p_actor_tg_id, ''))
  where c.hospital_id = trim(coalesce(p_hospital_id, ''))
    and c.enabled is true;

  return jsonb_build_object(
    'allowed', coalesce(v_access.allowed, false),
    'reason', case
      when coalesce(v_access.allowed, false) then null
      when coalesce(v_access.employee_access_enabled, false) is false then 'ADMIN_ONLY'
      else 'NO_HOSPITAL_RANK'
    end,
    'isAdmin', coalesce(v_access.is_admin, false),
    'employeeAccessEnabled', coalesce(v_access.employee_access_enabled, false),
    'rank', coalesce(v_access.rank, ''),
    'permissions', jsonb_build_object(
      'canRefill', coalesce(v_access.is_admin, false) or coalesce(v_access.rank_level, 0) >= 3,
      'canOrderFood', coalesce(v_access.is_admin, false) or coalesce(v_access.rank_level, 0) >= 2,
      'canManageEmployees', coalesce(v_access.is_admin, false) or coalesce(v_access.rank_level, 0) >= 3,
      'canViewStats', coalesce(v_access.is_admin, false) or coalesce(v_access.rank_level, 0) >= 3
    ),
    'items', v_items
  );
end;
$$;

create or replace function public.hospital_refill_stock(
  p_hospital_id text, p_actor_tg_id text, p_item_type text, p_quantity bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_access record;
  v_after bigint;
begin
  if coalesce(p_quantity, 0) <= 0 or p_quantity > 100000 then raise exception 'QUANTITY_INVALID'; end if;
  select * into v_access from public.hospital_get_actor_access(p_hospital_id, p_actor_tg_id);
  if not coalesce(v_access.allowed, false) then raise exception 'HOSPITAL_ACCESS_DENIED'; end if;
  if not v_access.is_admin and v_access.rank_level < 3 then raise exception 'REFILL_RANK_REQUIRED'; end if;

  update public.hospital_warehouse_stock
  set quantity = quantity + p_quantity, updated_by_tg_id = p_actor_tg_id, updated_at = now()
  where hospital_id = trim(p_hospital_id) and item_type = p_item_type
  returning quantity into v_after;
  if v_after is null then raise exception 'ITEM_NOT_FOUND'; end if;

  insert into public.hospital_stock_movements(hospital_id, actor_tg_id, item_type, movement_type, quantity, balance_after)
  values (trim(p_hospital_id), trim(p_actor_tg_id), p_item_type, 'refill', p_quantity, v_after);
  return jsonb_build_object('quantity', v_after);
end;
$$;

create or replace function public.hospital_take_stock(
  p_hospital_id text, p_actor_tg_id text, p_item_type text, p_quantity bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_access record;
  v_min_rank integer;
  v_after bigint;
begin
  if coalesce(p_quantity, 0) <= 0 or p_quantity > 100000 then raise exception 'QUANTITY_INVALID'; end if;
  select * into v_access from public.hospital_get_actor_access(p_hospital_id, p_actor_tg_id);
  if not coalesce(v_access.allowed, false) then raise exception 'HOSPITAL_ACCESS_DENIED'; end if;

  select min_take_rank into v_min_rank
  from public.hospital_item_catalog
  where hospital_id = trim(p_hospital_id) and item_type = p_item_type and enabled is true;
  if v_min_rank is null then raise exception 'ITEM_NOT_FOUND'; end if;
  if not v_access.is_admin and v_access.rank_level < v_min_rank then raise exception 'ITEM_RANK_REQUIRED'; end if;

  update public.hospital_warehouse_stock
  set quantity = quantity - p_quantity, updated_by_tg_id = p_actor_tg_id, updated_at = now()
  where hospital_id = trim(p_hospital_id) and item_type = p_item_type and quantity >= p_quantity
  returning quantity into v_after;
  if v_after is null then raise exception 'WAREHOUSE_STOCK_NOT_ENOUGH'; end if;

  insert into public.hospital_employee_inventory(hospital_id, employee_tg_id, item_type, quantity)
  values (trim(p_hospital_id), trim(p_actor_tg_id), p_item_type, p_quantity)
  on conflict (hospital_id, employee_tg_id, item_type) do update
    set quantity = hospital_employee_inventory.quantity + excluded.quantity, updated_at = now();

  insert into public.hospital_stock_movements(hospital_id, actor_tg_id, target_tg_id, item_type, movement_type, quantity, balance_after)
  values (trim(p_hospital_id), trim(p_actor_tg_id), trim(p_actor_tg_id), p_item_type, 'take', p_quantity, v_after);
  return jsonb_build_object('warehouseQuantity', v_after);
end;
$$;

create or replace function public.hospital_order_food(
  p_hospital_id text, p_actor_tg_id text, p_quantity bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_access record;
  v_order_id bigint;
begin
  if coalesce(p_quantity, 0) <= 0 or p_quantity > 100000 then raise exception 'QUANTITY_INVALID'; end if;
  select * into v_access from public.hospital_get_actor_access(p_hospital_id, p_actor_tg_id);
  if not coalesce(v_access.allowed, false) then raise exception 'HOSPITAL_ACCESS_DENIED'; end if;
  if not v_access.is_admin and v_access.rank_level < 2 then raise exception 'MIDDLE_RANK_REQUIRED'; end if;

  insert into public.hospital_supply_orders(hospital_id, quantity, ordered_by_tg_id)
  values (trim(p_hospital_id), p_quantity, trim(p_actor_tg_id))
  returning id into v_order_id;
  insert into public.hospital_stock_movements(hospital_id, actor_tg_id, item_type, movement_type, quantity, metadata)
  values (trim(p_hospital_id), trim(p_actor_tg_id), 'food', 'order_food', p_quantity, jsonb_build_object('orderId', v_order_id));
  return jsonb_build_object('orderId', v_order_id, 'status', 'pending');
end;
$$;

create or replace function public.hospital_list_employees(p_hospital_id text, p_actor_tg_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_access record;
  v_employees jsonb;
begin
  select * into v_access from public.hospital_get_actor_access(p_hospital_id, p_actor_tg_id);
  if not coalesce(v_access.allowed, false) or (not v_access.is_admin and v_access.rank_level < 3) then
    raise exception 'EMPLOYEE_MANAGEMENT_DENIED';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'tgId', he.employee_tg_id,
    'nickname', coalesce(p.nickname, 'Игрок'),
    'rank', he.rank,
    'playersTreated', coalesce(st.players_treated, 0),
    'medicinesSold', coalesce(st.medicines_sold, 0)
  ) order by public.hospital_rank_level(he.rank) desc, coalesce(p.nickname, he.employee_tg_id)), '[]'::jsonb)
  into v_employees
  from public.hospital_employees he
  left join public.players p on p.tg_id::text = he.employee_tg_id
  left join public.hospital_employee_stats st
    on st.hospital_id = he.hospital_id and st.employee_tg_id = he.employee_tg_id
  where he.hospital_id = trim(p_hospital_id) and he.active is true;

  return jsonb_build_object('employees', v_employees);
end;
$$;

create or replace function public.hospital_set_employee_rank(
  p_hospital_id text, p_actor_tg_id text, p_target text, p_rank text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_access record;
  v_target_tg_id text;
  v_target_current_rank text;
  v_rank text := lower(trim(coalesce(p_rank, '')));
begin
  if v_rank not in ('junior', 'middle', 'senior', 'dismissed') then raise exception 'RANK_INVALID'; end if;
  select * into v_access from public.hospital_get_actor_access(p_hospital_id, p_actor_tg_id);
  if not coalesce(v_access.allowed, false) or (not v_access.is_admin and v_access.rank_level < 3) then
    raise exception 'EMPLOYEE_MANAGEMENT_DENIED';
  end if;

  v_target_tg_id := public.hospital_resolve_player_tg_id(p_target);
  if v_target_tg_id is null then raise exception 'PLAYER_NOT_FOUND'; end if;
  if v_target_tg_id = trim(p_actor_tg_id) and not v_access.is_admin then raise exception 'CANNOT_CHANGE_OWN_RANK'; end if;

  select rank into v_target_current_rank
  from public.hospital_employees
  where hospital_id = trim(p_hospital_id) and employee_tg_id = v_target_tg_id and active is true;
  if not v_access.is_admin and (v_rank = 'senior' or v_target_current_rank = 'senior') then
    raise exception 'ADMIN_REQUIRED_FOR_SENIOR_RANK';
  end if;

  if v_rank = 'dismissed' then
    update public.hospital_employees
    set active = false, appointed_by_tg_id = trim(p_actor_tg_id), updated_at = now()
    where hospital_id = trim(p_hospital_id) and employee_tg_id = v_target_tg_id;
  else
    insert into public.hospital_employees(hospital_id, employee_tg_id, rank, appointed_by_tg_id, active)
    values (trim(p_hospital_id), v_target_tg_id, v_rank, trim(p_actor_tg_id), true)
    on conflict (hospital_id, employee_tg_id) do update
      set rank = excluded.rank, active = true, appointed_by_tg_id = excluded.appointed_by_tg_id, updated_at = now();
    insert into public.hospital_employee_stats(hospital_id, employee_tg_id)
    values (trim(p_hospital_id), v_target_tg_id)
    on conflict (hospital_id, employee_tg_id) do nothing;
  end if;

  return jsonb_build_object('tgId', v_target_tg_id, 'rank', v_rank);
end;
$$;

create or replace function public.hospital_get_stats(p_hospital_id text, p_actor_tg_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_access record;
  v_stats jsonb;
begin
  select * into v_access from public.hospital_get_actor_access(p_hospital_id, p_actor_tg_id);
  if not coalesce(v_access.allowed, false) or (not v_access.is_admin and v_access.rank_level < 3) then
    raise exception 'STATS_ACCESS_DENIED';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'tgId', st.employee_tg_id,
    'nickname', coalesce(p.nickname, 'Игрок'),
    'rank', coalesce(he.rank, 'dismissed'),
    'playersTreated', st.players_treated,
    'medicinesGiven', st.medicines_given,
    'medicinesSold', st.medicines_sold,
    'healthRestored', st.health_restored,
    'revenue', st.revenue
  ) order by st.players_treated desc, st.medicines_sold desc), '[]'::jsonb)
  into v_stats
  from public.hospital_employee_stats st
  left join public.hospital_employees he
    on he.hospital_id = st.hospital_id and he.employee_tg_id = st.employee_tg_id
  left join public.players p on p.tg_id::text = st.employee_tg_id
  where st.hospital_id = trim(p_hospital_id);
  return jsonb_build_object('stats', v_stats);
end;
$$;

create or replace function public.hospital_treat_player(
  p_hospital_id text, p_actor_tg_id text, p_target text, p_medicine_type text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_access record;
  v_patient_tg_id text;
  v_patient public.players%rowtype;
  v_catalog public.hospital_item_catalog%rowtype;
  v_patient_nickname text;
begin
  select * into v_access from public.hospital_get_actor_access(p_hospital_id, p_actor_tg_id);
  if not coalesce(v_access.allowed, false) then raise exception 'HOSPITAL_ACCESS_DENIED'; end if;

  select * into v_catalog
  from public.hospital_item_catalog
  where hospital_id = trim(p_hospital_id)
    and item_type = p_medicine_type
    and item_type like 'medicine_%'
    and enabled is true;
  if not found then raise exception 'MEDICINE_NOT_FOUND'; end if;
  if not v_access.is_admin and v_access.rank_level < v_catalog.min_treat_rank then raise exception 'TREATMENT_RANK_REQUIRED'; end if;

  v_patient_tg_id := public.hospital_resolve_player_tg_id(p_target);
  if v_patient_tg_id is null then raise exception 'PLAYER_NOT_FOUND'; end if;
  select * into v_patient from public.players where tg_id::text = v_patient_tg_id for update;
  v_patient_nickname := coalesce(v_patient.nickname, 'Игрок');
  if v_patient.food < v_catalog.min_food then raise exception 'PATIENT_FOOD_TOO_LOW'; end if;
  if v_patient.health >= 100 then raise exception 'PATIENT_HEALTH_FULL'; end if;
  if v_patient.health < v_catalog.min_health or v_patient.health >= v_catalog.max_health then
    raise exception 'MEDICINE_HEALTH_RANGE_MISMATCH';
  end if;
  if exists (
    select 1 from public.hospital_treatment_effects
    where patient_tg_id = v_patient_tg_id and status = 'active'
  ) then raise exception 'PATIENT_ALREADY_TREATED'; end if;

  update public.hospital_employee_inventory
  set quantity = quantity - 1, updated_at = now()
  where hospital_id = trim(p_hospital_id)
    and employee_tg_id = trim(p_actor_tg_id)
    and item_type = p_medicine_type
    and quantity >= 1;
  if not found then raise exception 'PERSONAL_MEDICINE_NOT_ENOUGH'; end if;

  insert into public.hospital_treatment_effects(
    hospital_id, patient_tg_id, clinician_tg_id, medicine_type,
    heal_per_tick, tick_seconds, expires_at
  ) values (
    trim(p_hospital_id), v_patient_tg_id, trim(p_actor_tg_id), p_medicine_type,
    v_catalog.heal_per_tick, v_catalog.tick_seconds, now() + make_interval(secs => v_catalog.duration_seconds)
  );

  insert into public.hospital_employee_stats(hospital_id, employee_tg_id, players_treated, medicines_given)
  values (trim(p_hospital_id), trim(p_actor_tg_id), 1, 1)
  on conflict (hospital_id, employee_tg_id) do update
    set players_treated = hospital_employee_stats.players_treated + 1,
        medicines_given = hospital_employee_stats.medicines_given + 1,
        updated_at = now();
  insert into public.hospital_stock_movements(hospital_id, actor_tg_id, target_tg_id, item_type, movement_type, quantity)
  values (trim(p_hospital_id), trim(p_actor_tg_id), v_patient_tg_id, p_medicine_type, 'treat', 1);

  return jsonb_build_object('patientTgId', v_patient_tg_id, 'patientNickname', v_patient_nickname, 'durationSeconds', v_catalog.duration_seconds);
end;
$$;

create or replace function public.hospital_sell_medicine(
  p_hospital_id text, p_actor_tg_id text, p_target text, p_medicine_type text, p_quantity bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_access record;
  v_buyer_tg_id text;
  v_catalog public.hospital_item_catalog%rowtype;
  v_total bigint;
begin
  if coalesce(p_quantity, 0) <= 0 or p_quantity > 1000 then raise exception 'QUANTITY_INVALID'; end if;
  select * into v_access from public.hospital_get_actor_access(p_hospital_id, p_actor_tg_id);
  if not coalesce(v_access.allowed, false) then raise exception 'HOSPITAL_ACCESS_DENIED'; end if;
  select * into v_catalog
  from public.hospital_item_catalog
  where hospital_id = trim(p_hospital_id) and item_type = p_medicine_type and item_type like 'medicine_%' and enabled is true;
  if not found then raise exception 'MEDICINE_NOT_FOUND'; end if;
  if not v_access.is_admin and v_access.rank_level < v_catalog.min_sell_rank then raise exception 'SALE_RANK_REQUIRED'; end if;
  if v_catalog.sale_price <= 0 then raise exception 'SALE_PRICE_NOT_CONFIGURED'; end if;

  v_buyer_tg_id := public.hospital_resolve_player_tg_id(p_target);
  if v_buyer_tg_id is null then raise exception 'PLAYER_NOT_FOUND'; end if;
  v_total := v_catalog.sale_price * p_quantity;

  update public.hospital_employee_inventory
  set quantity = quantity - p_quantity, updated_at = now()
  where hospital_id = trim(p_hospital_id) and employee_tg_id = trim(p_actor_tg_id)
    and item_type = p_medicine_type and quantity >= p_quantity;
  if not found then raise exception 'PERSONAL_MEDICINE_NOT_ENOUGH'; end if;

  update public.players
  set balance = balance - v_total
  where tg_id::text = v_buyer_tg_id and balance >= v_total;
  if not found then raise exception 'BUYER_BALANCE_NOT_ENOUGH'; end if;

  insert into public.player_medical_inventory(player_tg_id, item_type, quantity)
  values (v_buyer_tg_id, p_medicine_type, p_quantity)
  on conflict (player_tg_id, item_type) do update
    set quantity = player_medical_inventory.quantity + excluded.quantity, updated_at = now();
  update public.hospital_finances set balance = balance + v_total, updated_at = now()
  where hospital_id = trim(p_hospital_id);
  insert into public.hospital_employee_stats(hospital_id, employee_tg_id, medicines_sold, revenue)
  values (trim(p_hospital_id), trim(p_actor_tg_id), p_quantity, v_total)
  on conflict (hospital_id, employee_tg_id) do update
    set medicines_sold = hospital_employee_stats.medicines_sold + excluded.medicines_sold,
        revenue = hospital_employee_stats.revenue + excluded.revenue,
        updated_at = now();
  insert into public.hospital_stock_movements(hospital_id, actor_tg_id, target_tg_id, item_type, movement_type, quantity, metadata)
  values (trim(p_hospital_id), trim(p_actor_tg_id), v_buyer_tg_id, p_medicine_type, 'sell', p_quantity, jsonb_build_object('totalPrice', v_total));
  return jsonb_build_object('buyerTgId', v_buyer_tg_id, 'quantity', p_quantity, 'totalPrice', v_total);
end;
$$;

create or replace function public.hospital_process_my_treatment(p_patient_tg_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_effect public.hospital_treatment_effects%rowtype;
  v_health numeric(5,1);
  v_until timestamptz;
  v_ticks integer;
  v_heal numeric(8,2) := 0;
  v_actual_heal numeric(8,2) := 0;
  v_new_health numeric(5,1);
  v_active boolean := false;
  v_next_ms integer := 2000;
begin
  select * into v_effect
  from public.hospital_treatment_effects
  where patient_tg_id = trim(p_patient_tg_id) and status = 'active'
  order by started_at desc
  limit 1
  for update skip locked;

  select health into v_health from public.players where tg_id::text = trim(p_patient_tg_id) for update;
  if v_health is null then raise exception 'PLAYER_NOT_FOUND'; end if;
  if v_effect.id is null then
    return jsonb_build_object('active', false, 'health', v_health, 'healed', 0, 'nextPollMs', 0);
  end if;

  v_until := least(now(), v_effect.expires_at);
  v_ticks := greatest(0, floor(extract(epoch from (v_until - v_effect.last_processed_at)) / v_effect.tick_seconds)::integer);

  if v_ticks > 0 then
    v_heal := v_ticks * v_effect.heal_per_tick;
    v_new_health := least(100::numeric, v_health + v_heal);
    v_actual_heal := greatest(0::numeric, v_new_health - v_health);
    update public.players set health = v_new_health where tg_id::text = trim(p_patient_tg_id);
    v_health := v_new_health;
    update public.hospital_treatment_effects
    set last_processed_at = last_processed_at + make_interval(secs => v_ticks * tick_seconds)
    where id = v_effect.id;
    v_effect.last_processed_at := v_effect.last_processed_at + make_interval(secs => v_ticks * v_effect.tick_seconds);
    update public.hospital_employee_stats
    set health_restored = health_restored + v_actual_heal, updated_at = now()
    where hospital_id = v_effect.hospital_id and employee_tg_id = v_effect.clinician_tg_id;
  end if;

  if now() >= v_effect.expires_at or v_health >= 100 then
    update public.hospital_treatment_effects set status = 'completed' where id = v_effect.id;
    v_active := false;
    v_next_ms := 0;
  else
    v_active := true;
    v_next_ms := greatest(500, least(10000,
      ceil(v_effect.tick_seconds * 1000 - extract(epoch from (now() - v_effect.last_processed_at)) * 1000)::integer
    ));
  end if;

  return jsonb_build_object('active', v_active, 'health', v_health, 'healed', v_actual_heal, 'nextPollMs', v_next_ms);
end;
$$;

revoke all on table public.hospital_settings from anon, authenticated;
revoke all on table public.hospital_item_catalog from anon, authenticated;
revoke all on table public.hospital_warehouse_stock from anon, authenticated;
revoke all on table public.hospital_employees from anon, authenticated;
revoke all on table public.hospital_employee_inventory from anon, authenticated;
revoke all on table public.hospital_supply_orders from anon, authenticated;
revoke all on table public.hospital_stock_movements from anon, authenticated;
revoke all on table public.hospital_employee_stats from anon, authenticated;
revoke all on table public.hospital_finances from anon, authenticated;
revoke all on table public.player_medical_inventory from anon, authenticated;
revoke all on table public.hospital_treatment_effects from anon, authenticated;

revoke all on function public.hospital_rank_level(text) from public, anon, authenticated;
revoke all on function public.hospital_player_is_admin(text) from public, anon, authenticated;
revoke all on function public.hospital_resolve_player_tg_id(text) from public, anon, authenticated;
revoke all on function public.hospital_ensure(text) from public, anon, authenticated;
revoke all on function public.hospital_get_actor_access(text, text) from public, anon, authenticated;
revoke all on function public.hospital_get_context(text, text) from public, anon, authenticated;
revoke all on function public.hospital_refill_stock(text, text, text, bigint) from public, anon, authenticated;
revoke all on function public.hospital_take_stock(text, text, text, bigint) from public, anon, authenticated;
revoke all on function public.hospital_order_food(text, text, bigint) from public, anon, authenticated;
revoke all on function public.hospital_list_employees(text, text) from public, anon, authenticated;
revoke all on function public.hospital_set_employee_rank(text, text, text, text) from public, anon, authenticated;
revoke all on function public.hospital_get_stats(text, text) from public, anon, authenticated;
revoke all on function public.hospital_treat_player(text, text, text, text) from public, anon, authenticated;
revoke all on function public.hospital_sell_medicine(text, text, text, text, bigint) from public, anon, authenticated;
revoke all on function public.hospital_process_my_treatment(text) from public, anon, authenticated;

grant execute on function public.hospital_get_context(text, text) to service_role;
grant execute on function public.hospital_refill_stock(text, text, text, bigint) to service_role;
grant execute on function public.hospital_take_stock(text, text, text, bigint) to service_role;
grant execute on function public.hospital_order_food(text, text, bigint) to service_role;
grant execute on function public.hospital_list_employees(text, text) to service_role;
grant execute on function public.hospital_set_employee_rank(text, text, text, text) to service_role;
grant execute on function public.hospital_get_stats(text, text) to service_role;
grant execute on function public.hospital_treat_player(text, text, text, text) to service_role;
grant execute on function public.hospital_sell_medicine(text, text, text, text, bigint) to service_role;
grant execute on function public.hospital_process_my_treatment(text) to service_role;

-- Примеры дальнейшей настройки (не выполняются автоматически):
-- update public.hospital_settings
-- set employee_access_enabled = true, updated_at = now()
-- where hospital_id = 'ID_БОЛЬНИЦЫ';
--
-- update public.hospital_item_catalog set sale_price = 100
-- where hospital_id = 'ID_БОЛЬНИЦЫ' and item_type = 'medicine_light';
