import './industryMiniGames.css';
import { INDUSTRY_ROLES } from './industryConfig.js';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);

function shell(role){return `<div class="mn-industry-game" data-industry-game><button data-game-cancel></button><section data-mode="${role.game}"><header><i>${role.icon}</i><span><small>ПРОИЗВОДСТВЕННАЯ СМЕНА</small><strong>${esc(role.label)}</strong></span><b data-game-score>0/5</b></header><main data-game-stage></main><footer><small data-game-hint>Приготовьтесь…</small><button data-game-action>Начать</button></footer></section></div>`;}
function timing(stage){stage.innerHTML='<div class="mn-timing"><i></i><b></b></div>';let x=0,dir=1,timer=setInterval(()=>{x+=dir*2.8;if(x>96||x<0)dir*=-1;stage.style.setProperty('--x',`${x}%`)},16);return()=>{clearInterval(timer);return x>38&&x<62;};}
function sorting(stage,onHit){const good=Math.floor(Math.random()*6);stage.innerHTML=`<div class="mn-sorting">${[0,1,2,3,4,5].map(i=>`<button data-pick="${i}"${i===good?' data-good="true"':''}>${i===good?'✅':'❌'}</button>`).join('')}</div>`;return()=>new Promise(resolve=>{stage.onclick=e=>{const b=e.target.closest('[data-pick]');if(!b)return;const ok=b.dataset.good==='true';onHit(ok);resolve(ok);};});}
function packing(stage,onHit){const order=shuffle(['1','2','3','4']);stage.innerHTML=`<div class="mn-packing">${order.map(v=>`<button data-box="${v}">${v}</button>`).join('')}</div>`;let next=1;return()=>new Promise(resolve=>{stage.onclick=e=>{const b=e.target.closest('[data-box]');if(!b)return;const ok=Number(b.dataset.box)===next;b.disabled=true;if(!ok){onHit(false);resolve(false);}else if(++next===5){onHit(true);resolve(true);}};});}
function inspection(stage,onHit){const defect=Math.floor(Math.random()*5);stage.innerHTML=`<div class="mn-inspection">${[0,1,2,3,4].map(i=>`<button data-part="${i}"${i===defect?' data-defect="true"':''}>⚙️</button>`).join('')}</div>`;return()=>new Promise(resolve=>{stage.onclick=e=>{const b=e.target.closest('[data-part]');if(!b)return;const ok=b.dataset.defect==='true';onHit(ok);resolve(ok);};});}
function loading(stage){stage.innerHTML='<div class="mn-loading"><b>📦</b><span></span><i></i></div>';let power=0,down=false;const press=()=>{down=true},up=()=>{down=false};stage.onpointerdown=press;window.addEventListener('pointerup',up);const timer=setInterval(()=>{power=Math.max(0,Math.min(100,power+(down?2.7:-1.2)));stage.style.setProperty('--power',`${power}%`)},16);return()=>{clearInterval(timer);window.removeEventListener('pointerup',up);return power>=55&&power<=82;};}
function forklift(stage,onHit){const target=1+Math.floor(Math.random()*3);stage.innerHTML=`<div class="mn-forklift"><b>🚜</b>${[1,2,3].map(i=>`<button data-bay="${i}">Сектор ${i}</button>`).join('')}<small>Накладная: сектор ${target}</small></div>`;return()=>new Promise(resolve=>{stage.onclick=e=>{const b=e.target.closest('[data-bay]');if(!b)return;const ok=Number(b.dataset.bay)===target;onHit(ok);resolve(ok);};});}
const builders={timing,sorting,packing,inspection,loading,forklift};
export function playIndustryMiniGame(roleId){const role=INDUSTRY_ROLES[roleId]||INDUSTRY_ROLES.loader;document.querySelector('[data-industry-game]')?.remove();document.body.insertAdjacentHTML('beforeend',shell(role));const root=document.querySelector('[data-industry-game]'),stage=root.querySelector('[data-game-stage]'),action=root.querySelector('[data-game-action]'),score=root.querySelector('[data-game-score]'),hint=root.querySelector('[data-game-hint]');return new Promise(resolve=>{let round=0,hits=0,active=null,locked=false;const finish=async ok=>{hits+=ok?1:0;round++;score.textContent=`${hits}/5`;hint.textContent=ok?'Выполнено точно':'Ошибка операции';await wait(350);if(round>=5){root.remove();resolve({success:hits>=3,score:hits,quality:Math.round(hits/5*100)});return;}start();};const start=()=>{locked=false;action.textContent=role.game==='timing'||role.game==='loading'?'Зафиксировать':'Выполнить';hint.textContent=`Этап ${round+1} из 5`;active=builders[role.game](stage,ok=>{if(locked)return;locked=true;void finish(ok)});if(active instanceof Function&&(role.game==='sorting'||role.game==='packing'||role.game==='inspection'||role.game==='forklift'))active();};action.onclick=()=>{if(!active){start();return;}if(locked)return;const result=active();if(typeof result==='boolean'){locked=true;void finish(result);}};root.querySelector('[data-game-cancel]').onclick=()=>{root.remove();resolve({success:false,cancelled:true,score:hits,quality:0})};action.textContent='Начать';});}
